apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

# Undeployed for now
# resources:
#   - ../../../base/media/homarr/
#
# patches:
#   - path: node-affinity-patch.yaml
