apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threadfin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: threadfin.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: threadfin
                port:
                  number: 34400
