apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - node-disk.yaml
  #- node-disk-nfs.yaml
  - storageclass-longhorn-config.yaml
  - secret.yaml

