apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-config
provisioner: driver.longhorn.io
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  replicaAutoBalance: "disabled"
  # This links the new volumes to the job above
  recurringJobSelector: '[{"name":"s3-weekly", "isGroup":true}]'
