apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - timescale-statefulset.yaml
  - redis-deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - secret.yaml
