apiVersion: v1
kind: Service
metadata:
  name: tracearr
  labels:
    app: tracearr
spec:
  type: ClusterIP
  selector:
    app: tracearr
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tracearr-timescale
  labels:
    app: tracearr-timescale
spec:
  type: ClusterIP
  selector:
    app: tracearr-timescale
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tracearr-redis
  labels:
    app: tracearr-redis
spec:
  type: ClusterIP
  selector:
    app: tracearr-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
